export const dynamicObjectData = [
    {
        type: "list",
        expanded: false,
        img: "./img/KaExpertise.png",
        hoverImg: "./img/KaExpertise-(Hover-Zustand).png",
        size: "large",
        data: [
            {
                type: "list",
                expanded: false,
                text: "Management Consulating",
                img: "./img/BallHoverState.png",
                hoverImg: "./img/BallHoverStatev2.png",
                size: "medium",
                data: [
                    {
                        type: "text",
                        expanded: false,
                        size: "small",
                        text: "expert guidence",
                        img: "./img/BallHoverState.png",
                        hoverImg: "./img/BallHoverStatev2.png",
                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                    },
                    {
                        type: "text",
                        expanded: false,
                        size: "small",
                        text: "strategic planning",
                        img: "./img/BallHoverState.png",
                        hoverImg: "./img/BallHoverStatev2.png",
                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                    },
                    {
                        type: "text",
                        expanded: false,
                        size: "medium",
                        text: "orks implementation",
                        img: "./img/BallHoverState.png",
                        hoverImg: "./img/BallHoverStatev2.png",
                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                    },
                    {
                        type: "text",
                        expanded: false,
                        size: "small",
                        text: "project management",
                        img: "./img/BallHoverState.png",
                        hoverImg: "./img/BallHoverStatev2.png",
                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                    },
                ],
            },
            {
                type: "text",
                expanded: false,
                size: "small",
                text: "about us",
                img: "./img/BallHoverState.png",
                hoverImg: "./img/BallHoverStatev2.png",
                data: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae ducimus molestias eum perferendis quis suscipit vel vitae laborum, odio explicabo, dolorum placeat eos officiis tempore.",
            },
            {
                type: "list",
                expanded: false,
                size: "medium",
                text: "software development",
                img: "./img/BallHoverState.png",
                hoverImg: "./img/BallHoverStatev2.png",
                data: [
                    {
                        type: "text",
                        expanded: false,
                        size: "small",
                        text: "free your genius",
                        img: "./img/BallHoverState.png",
                        hoverImg: "./img/BallHoverStatev2.png",
                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                    },
                    {
                        type: "text",
                        expanded: false,
                        size: "small",
                        text: "experties",
                        img: "./img/BallHoverState.png",
                        hoverImg: "./img/BallHoverStatev2.png",
                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                    },
                    {
                        type: "text",
                        expanded: false,
                        size: "small",
                        text: "our promise",
                        img: "./img/BallHoverState.png",
                        hoverImg: "./img/BallHoverStatev2.png",
                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                    },
                ],
            },
            {
                type: "text",
                expanded: false,
                text: "contact us",
                size: "small",
                img: "./img/BallHoverState.png",
                hoverImg: "./img/BallHoverStatev2.png",
                data: "",
            },
            {
                type: "list",
                expanded: false,
                size: "medium",
                text: "software product",
                img: "./img/BallHoverState.png",
                hoverImg: "./img/BallHoverStatev2.png",
                data: [
                    {
                        type: "text",
                        expanded: false,
                        size: "small",
                        img: "./img/BallHoverState.png",
                        hoverImg: "./img/BallHoverStatev2.png",
                        text: "ka fractal",
                        data: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas reiciendis minus doloremque, error repudiandae rerum?'
                    },
                    {
                        type: "text",
                        expanded: false,
                        size: "small",
                        img: "./img/BallHoverState.png",
                        hoverImg: "./img/BallHoverStatev2.png",
                        text: "emody your vision",
                        data: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolor, nemo eveniet ratione maxime itaque aspernatur maiores perferendis! Autem, velit. Corporis?'
                    },
                    {
                        type: "list",
                        expanded: false,
                        size: "small",
                        text: "planet test",
                        img: "./img/BallHoverState.png",
                        hoverImg: "./img/BallHoverStatev2.png",
                        data: [
                            {
                                type: "list",
                                expanded: false,
                                size: "small",
                                text: "Start 1",
                                img: "./img/BallHoverState.png",
                                hoverImg: "./img/BallHoverStatev2.png",
                                data: [
                                    {
                                        type: "text",
                                        expanded: false,
                                        size: "small",
                                        text: "A",
                                        img: "./img/BallHoverState.png",
                                        hoverImg: "./img/BallHoverStatev2.png",
                                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                                    },
                                    {
                                        type: "text",
                                        expanded: false,
                                        size: "small",
                                        text: "B",
                                        img: "./img/BallHoverState.png",
                                        hoverImg: "./img/BallHoverStatev2.png",
                                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                                    },
                                ],
                            },
                            {
                                type: "list",
                                expanded: false,
                                size: "small",
                                text: "Start 2",
                                img: "./img/BallHoverState.png",
                                hoverImg: "./img/BallHoverStatev2.png",
                                data: [
                                    {
                                        type: "text",
                                        expanded: false,
                                        text: "C",
                                        size: "small",
                                        img: "./img/BallHoverState.png",
                                        hoverImg: "./img/BallHoverStatev2.png",
                                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                                    },
                                    {
                                        type: "text",
                                        expanded: false,
                                        text: "D",
                                        size: "small",
                                        img: "./img/BallHoverState.png",
                                        hoverImg: "./img/BallHoverStatev2.png",
                                        data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
            {
                type: "text",
                expanded: false,
                text: "news",
                size: "small",
                img: "./img/BallHoverState.png",
                hoverImg: "./img/BallHoverStatev2.png",
                data: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corrupti harum cum doloribus quia officia voluptate?",
            },
        ],
    },
];
